public enum AlertType
{
    None = -1,
    Bag = 0,
    Mail = 1,
    Character = 2,
    Equipment = 3,
    EquipmentUpgrade = 4,
    EquipmentGemSlot = 5,
    HeroesHouse = 6,
    HeroesHouseFriend = 7,
    HeroesHouseInstigate = 8,
    HeroesHouseContract = 9,
    AuctionBid = 10,
    AuctionCollect = 11,
    AuctionRecord = 12,
    Crafting = 13,
    HeroBook = 14,
    Lottery = 15,
    LotteryFocus = 16,
    Guild = 17,
    GuildInfo = 18,
    GuildTech = 19,
    Talent = 20,
    TalentCultivate = 21,
    TalentAttribute = 22,
    TalentPoint = 23,
    Arena = 24,
    ArenaReward = 25,
    MenuOther = 26,
    MenuPersonal = 27,
    CharacterBag = 28,
    MenuMall = 29,
    Auction = 30,
    MenuSpend = 31,
    WelfareFirstTopUp = 32,
    HeroesHouseTech = 33,
    HeroesHouseHero = 34,
    WelfareSignInPrize = 35,
    WelfareOnlinePrize = 36,
    WelfareOpenServiceFund = 37,
    WelfareTotalGoldCredit = 38,
    WelfareTotalGoldSpend = 39,
    WelfareDailyGold = 40,
    WelfareGoldJackpot = 41,
    WelfareMain = 42,
    SevenDaysMain = 43,
    DungeonMenu = 44,
    DungeonStory = 45,
    DungeonDaily = 46,
    DungeonSpecial = 47,
    WorldBoss = 48,
    MenuOther_Character = 49,
    MenuOther_Challenge = 50,
    MenuOther_Social = 51,
    VIP = 52,
    OfflineExp = 53,
    Friends = 54,
    FriendRequest = 55,
    GuildActivity = 56,
    GuildSMBoss = 57,
    GuildWishingPool = 58,
    SkillCombo = 59,
    SkillComboRecommend = 60,
    Portrait = 61,
    QuestExtraRewardsMain = 62,
    MartialArts = 63,
    EliteMap = 64,

    MartialArts_Attack = 65,
    MartialArts_Health = 66,
    MartialArts_Armor = 67,
    MartialArts_Accuracy = 68,
    MartialArts_CriticalDef = 69,
    MartialArts_Critical = 70,
    MartialArts_Evasion = 71,
    MartialArts_CrititalResist = 72,
    MartialArts_CrititalPercent = 73,

    WelfareLoginReward = 74,

    Pet = 75,

    TutorialList = 76,
    TutorialList_Equip = 77,
    TutorialList_HeroesBook = 78,
    TutorialList_SkillsCombo = 79,
    TutorialList_Pet = 80,
    TutorialList_EquipGem = 81,

    ArenaFreeCount= 82,

    NUM,
}