//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using ExitGames.Client.Photon;
//using ExitGames.Client.Photon.Lite;

public class ClientRPCBase : RPCBase
{
	public ClientRPCBase (Type t, byte code)
		: base (t, code)
	{
	}

	public void SendCommand(Dictionary<byte, object> dic)
	{
		PhotonNetwork.networkingPeer.OpCustom (GetOpCode(), dic, true);
	}
}

