//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//#define DEBUGLOG	// uncomment this macro when build 

using UnityEngine;


public static class LogManager
{
	static LogManager ()
	{
	}

	public static void DebugLog(string msg)
	{
	#if DEBUGLOG
		Debug.Log (msg);
	#endif
	}
}


